name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17.5"
      - name: generate.sh
        run: |
          go get -u github.com/technosophos/dashing
          cd $GITHUB_WORKSPACE
          ./generate.sh
