name: Update

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17.5"
      - name: checkout.sh
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          go get -u github.com/technosophos/dashing
          git config user.email "67558040+midouest@users.noreply.github.com"
          git config user.name "midouest"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          cd $GITHUB_WORKSPACE
          ./checkout.sh
          git update-index --refresh
          git diff-index --quiet HEAD --
          if [ $? -eq 0 ]; then
            exit 0
          fi
          VERSION=$(cd norns && echo $(git tag -l "v*" --sort=-v:refname | head -n 1))
          git add norns
          git commit -m "update norns submodule to ${VERSION}"
          git push origin main
